Add testing/certutil/ package for TLS test support
elastic/elastic-agent-libs pull request #189
Opened 2024-03-11 15:41 UTC by AndersonQ

## What does this PR do?

Adds the `testing/certutil/` package providing on-the-fly generation of TLS certificate and root CA and a CLI to generate them as well.

## Why is it important?

The Elastic Agent and Bats need to configure TLS for testing. This provide an easy way to generate the needed certificates without duplicating code in the Elastic Agent and Beats repo

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- ~~[ ] I have added tests that prove my fix is effective or that my feature works~~

## Related issues

- Relates elastic/elastic-agent/issues/2247

2024-03-11 15:47 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/elastic-agent-libs/builds/210)
* Commit: b45f19396c670c469b8c24e99b30e74a1510224b

cc @AndersonQ

<!--buildkite-pr-comment-elastic-agent-libs
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/elastic-agent-libs/builds/210","number":210,"commit":"b45f19396c670c469b8c24e99b30e74a1510224b"}],"number":210}
buildkite-pr-comment-->

2024-03-11 15:54 UTC, leehinman commented
I am strongly in favor of generating the CA & certs as needed for testing.  But do we need to write our own utility?

https://github.com/cloudflare/cfssl

Already does all of this, is go so we can embed in our tests, and has been around a while so most of the subtle X509 considerations have been addressed.

Downside is that we don't build up as much X509 knowledge in our team.  Thoughts?

2024-03-11 17:16 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/elastic-agent-libs/builds/211)
* Commit: e02cbccfb1bdb2e4862c718b1a15d47e5c8a42e1

### History
* :green_heart: [Build #210](https://buildkite.com/elastic/elastic-agent-libs/builds/210) succeeded b45f19396c670c469b8c24e99b30e74a1510224b

cc @AndersonQ

<!--buildkite-pr-comment-elastic-agent-libs
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/elastic-agent-libs/builds/211","number":211,"commit":"e02cbccfb1bdb2e4862c718b1a15d47e5c8a42e1"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/elastic-agent-libs/builds/210","number":210,"commit":"b45f19396c670c469b8c24e99b30e74a1510224b"}],"number":211}
buildkite-pr-comment-->

2024-03-12 11:10 UTC, AndersonQ commented
> I am strongly in favor of generating the CA & certs as needed for testing. But do we need to write our own utility?
> 
> https://github.com/cloudflare/cfssl
> 
> Already does all of this, is go so we can embed in our tests, and has been around a while so most of the subtle X509 considerations have been addressed.
> 
> Downside is that we don't build up as much X509 knowledge in our team. Thoughts?

I was having a look at it. It feels overkill and I'd bet getting used to use it would not be much different than using what this PR adds. Also as you pointed, by building it ourselves we get some more knowledge in the team about how all the moving pieces get together.

Lastly, it's done already, the beats use a similar code that can, and should, be replaced by this new package. Just the work to replace this PR and instead use `github.com/cloudflare/cfssl` would not be worth.

2024-03-12 14:32 UTC, leehinman requested changes

2024-03-19 16:13 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/elastic-agent-libs/builds/214)
* Commit: b45f19396c670c469b8c24e99b30e74a1510224b

### History
* :broken_heart: [Build #212](https://buildkite.com/elastic/elastic-agent-libs/builds/212) failed f8c32aedef2960449f9423ec59eeb21ce9322fea
* :green_heart: [Build #211](https://buildkite.com/elastic/elastic-agent-libs/builds/211) succeeded e02cbccfb1bdb2e4862c718b1a15d47e5c8a42e1
* :green_heart: [Build #210](https://buildkite.com/elastic/elastic-agent-libs/builds/210) succeeded b45f19396c670c469b8c24e99b30e74a1510224b

cc @AndersonQ

<!--buildkite-pr-comment-elastic-agent-libs
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/elastic-agent-libs/builds/214","number":214,"commit":"b45f19396c670c469b8c24e99b30e74a1510224b"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/elastic-agent-libs/builds/212","number":212,"commit":"f8c32aedef2960449f9423ec59eeb21ce9322fea"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/elastic-agent-libs/builds/211","number":211,"commit":"e02cbccfb1bdb2e4862c718b1a15d47e5c8a42e1"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/elastic-agent-libs/builds/210","number":210,"commit":"b45f19396c670c469b8c24e99b30e74a1510224b"}],"number":214}
buildkite-pr-comment-->

2024-03-21 14:05 UTC, AndersonQ commented
as discussed directly with @leehinman, the child certificate generation will be improved on another PR and use the `Certificate Request`

2024-03-21 14:09 UTC, leehinman approved these changes

2024-03-21 14:09 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/elastic-agent-libs/builds/216)
* Commit: 1f677883d2e77d768276fd02df1a2ed8db149cbf

### History
* :green_heart: [Build #214](https://buildkite.com/elastic/elastic-agent-libs/builds/214) succeeded b45f19396c670c469b8c24e99b30e74a1510224b
* :broken_heart: [Build #212](https://buildkite.com/elastic/elastic-agent-libs/builds/212) failed f8c32aedef2960449f9423ec59eeb21ce9322fea
* :green_heart: [Build #211](https://buildkite.com/elastic/elastic-agent-libs/builds/211) succeeded e02cbccfb1bdb2e4862c718b1a15d47e5c8a42e1
* :green_heart: [Build #210](https://buildkite.com/elastic/elastic-agent-libs/builds/210) succeeded b45f19396c670c469b8c24e99b30e74a1510224b

cc @AndersonQ

<!--buildkite-pr-comment-elastic-agent-libs
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/elastic-agent-libs/builds/216","number":216,"commit":"1f677883d2e77d768276fd02df1a2ed8db149cbf"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/elastic-agent-libs/builds/214","number":214,"commit":"b45f19396c670c469b8c24e99b30e74a1510224b"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/elastic-agent-libs/builds/212","number":212,"commit":"f8c32aedef2960449f9423ec59eeb21ce9322fea"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/elastic-agent-libs/builds/211","number":211,"commit":"e02cbccfb1bdb2e4862c718b1a15d47e5c8a42e1"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/elastic-agent-libs/builds/210","number":210,"commit":"b45f19396c670c469b8c24e99b30e74a1510224b"}],"number":216}
buildkite-pr-comment-->

2024-03-21 14:29 UTC, merged