tlscommon: fix EC key decryption
elastic/elastic-agent-libs pull request #190
Opened 2024-03-18 17:10 UTC by AndersonQ

## What does this PR do?

Fix how encrypted TLS certificate keys are handled. `x509.DecryptPEMBlock` returns a PEM block, and the code would assume it was not in PEM format and was re-encoding it into PEM, which would generate an invalid key.

## Why is it important?

Without the fix, it breaks when parsing a certificate key 

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works

## Author's Checklist

- [ ]

## Related issues

- Relates https://github.com/elastic/elastic-agent/issues/2247
- Relates https://github.com/elastic/elastic-agent/issues/2248

2024-03-18 17:11 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/elastic-agent-libs/builds/213)
* Commit: 4c2d07cecc747b1c81eb58de78fdb5aa4b6c16a8

### Failed CI Steps
* [:linux: Test Linux](https://buildkite.com/elastic/elastic-agent-libs/builds/213#018e528b-72e2-4cbb-a738-92ce34d54166)

cc @AndersonQ

<!--buildkite-pr-comment-elastic-agent-libs
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/elastic-agent-libs/builds/213","number":213,"commit":"4c2d07cecc747b1c81eb58de78fdb5aa4b6c16a8"}],"number":213}
buildkite-pr-comment-->

2024-03-18 18:01 UTC, cmacknz commented
Needs a test

2024-03-18 18:48 UTC, leehinman requested changes
needs tests

2024-03-18 18:48 UTC, leehinman commented on transport/tlscommon/tls.go
> +			// not encrypted and not in PEM format, encode it.
Is this function only used for reading PEM encoded private keys?  The implementation suggests that, but the function name and signature don't.  If this were to read a PEM encoded certificate, you don't want to re-encode.

As it stands, I think the default case is trying to catch if they actually supplied a DER encoded private key.  If that is the case it is probably worth checking to see if `ParsePKIXPublicKey` works and to log at the warn level that DER format was provided but PEM format was expected.

2024-03-19 15:46 UTC, AndersonQ commented
`x509.DecryptPEMBlock` should receive a DER encoded key, not a PEM encoded. That way the key it returns will always be in DER format and we need to encode it as PEM. Thus the code is actually correct

2024-03-19 15:46 UTC, closed without merging