Extract function `SyncParent` to reuse in elastic agent
elastic/elastic-agent-libs pull request #36
Opened 2022-04-07 11:46 UTC by narph

Related to https://github.com/elastic/elastic-agent/issues/98

We need to sync parent after file is synced, this does not happen in function https://github.com/elastic/elastic-agent/blob/main/internal/pkg/agent/storage/replace_store.go#L107

2022-04-07 11:54 UTC, elasticmachine commented
## :grey_exclamation: Build Aborted
  
  > There is a new build on-going so the previous on-going builds have been aborted.
  


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Felastic-agent-libs-mbp%2FPR-36/detail/PR-36/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Felastic-agent-libs-mbp%2FPR-36/detail/PR-36/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Felastic-agent-libs-mbp%2FPR-36/detail/PR-36/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Felastic-agent-libs-mbp%2FPR-36/detail/PR-36/1//artifacts)   [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/beats-ci/transactions/view?rangeFrom=2022-04-07T11:36:31.114Z&rangeTo=2022-04-07T11:56:31.114Z&transactionName=BUILD+Ingest-manager/elastic-agent-libs-mbp/PR-{number}&transactionType=job&latencyAggregationType=avg&traceId=9493a9967ddc4dda5968b117e31833a3&transactionId=f73b42f4f662f54b)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2022-04-07T11:46:31.114+0000


* Duration: 8 min 9 sec




#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 0  |
| Passed       | 67  |
| Skipped      | 0 |
| Total        | 67   |


</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->












### Steps errors [![1](https://img.shields.io/badge/1%20-red)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Felastic-agent-libs-mbp%2FPR-36/detail/PR-36/1//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>


  
  
  
  
##### `Running Go tests`
<ul>
<li>Took 0 min 10 sec . View more details <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/elastic-agent-libs-mbp/pipelines/PR-36/runs/1/steps/265/log/?start=0">here</a></li>
<li>Description: <code>gotestsum --format testname --junitfile junit-report.xml -- -v ./...</code></l1>
</ul>
  
  </p>
  </details>



## :robot: GitHub comments

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2022-04-07 14:38 UTC, blakerouse approved these changes
Extraction looks good.

2022-04-07 18:23 UTC, ph requested changes
Your implementation LGTM.

But there is something that bugs me in the files:

- If you look at the `file/helper_windows.go` the name of the file mention windows but there is no build tag defined.
- If you look at `file/helper_other.go` there twice the build tags, we should clean it up.
- If you look at `file/helper_aix.go` There is no build tag and I think we should remove it since we do not support officially aix.

I think we should clean the files and rename them appropriately to really understand what files is actually used in the build, for me it's unclear. Unless I've missed a feature in Go that automatically picks up the code based on the file suffix?

2022-04-11 13:57 UTC, narph commented
> 

same issues with `fileinfo-*` and `stderr-*` in the directory, @kvch what is the plan for the those files, can we make the same changes recommended by @ph  to all files?

2022-04-12 10:58 UTC, kvch commented
> If you look at file/helper_other.go there twice the build tags, we should clean it up.

FYI, the build tags are there twice because there was a change in the format of build tags. We did not remove the old format, so older Golang versions can be used. I am fine with removing it.

> I think we should clean the files and rename them appropriately to really understand what files is actually used in the build, for me it's unclear. Unless I've missed a feature in Go that automatically picks up the code based on the file suffix.

Golang indeed decides what files to build based on file suffixes: https://dave.cheney.net/2013/10/12/how-to-use-conditional-compilation-with-the-go-build-tool

I am fine with bringing consistency to the files. However, my concern is enforcing the consistency. It is great that it bugs some people, but not everyone has the same desire for consistency. We can spend a few minutes/hours on making sure build tags/file suffixes are the same, but it will be all in vain if a new person comes who does not have the same internal goal or does not spend enough time in the codebase for realizing that there is a pattern. Can we enforce it somehow? Maybe the linter already has a checker for this we could enable?

2022-04-12 11:07 UTC, narph commented
@ph , @kvch can we take this separately in a different issue, would be great to take this fix in as soon as we can

2022-04-12 14:26 UTC, ph approved these changes
Agree, lets create an issue to clean that up.

2022-04-12 14:29 UTC, merged